@startuml CustomerControllers
class CustomerController {
    - <<readonly>> _logger : ILogger<CustomerController>
    - <<readonly>> _service : CustomerService
    + CustomerController(logger:ILogger<CustomerController>, service:CustomerService)
    + <<async>> GetCustomers(ct:CancellationToken) : Task<IActionResult>
    + <<async>> GetCustomer(customerId:string, ct:CancellationToken) : Task<IActionResult>
}
ControllerBase <|-- CustomerController
@enduml
