@startuml
class HealthCheckResilienceService {
    - <<readonly>> _logger : ILogger<HealthCheckResilienceService>?
    - <<readonly>> _service : HealthCheckService
    + HealthCheckResilienceService(logger:ILogger<HealthCheckResilienceService>?, service:HealthCheckService)
    - <<const>> MAX_RETRIES : int = 10
    - <<const>> RETRY_DELAY : int = 5
    + <<async>> WaitForHealthyStatusAsync(cancellationToken:CancellationToken) : Task
    + <<async>> RunManuallyAsync(cancellationToken:CancellationToken) : Task
    + <<async>> StartAsync(cancellationToken:CancellationToken) : Task
    + StopAsync(cancellationToken:CancellationToken) : Task
}
IHostedService <|-- HealthCheckResilienceService
@enduml
