@startuml HealthCheckResilienceService
class HealthCheckResilienceService {
    - <<readonly>> _logger : ILogger<HealthCheckResilienceService>?
    - <<readonly>> _service : HealthCheckService
    + HealthCheckResilienceService(logger:ILogger<HealthCheckResilienceService>?, service:HealthCheckService)
    - <<const>> MAX_RETRIES : int = 10
    - <<const>> RETRY_DELAY : int = 5
    + <<async>> WaitForHealthyStatusAsync(ct:CancellationToken) : Task
    + <<async>> RunManuallyAsync(ct:CancellationToken) : Task
    + <<async>> StartAsync(ct:CancellationToken) : Task
    + StopAsync(ct:CancellationToken) : Task
}
IHostedService <|-- HealthCheckResilienceService
@enduml
