@startuml
class NorthwindService {
    - <<readonly>> _logger : ILogger<NorthwindService>
    - <<readonly>> _repository : NorthwindRepository
    + NorthwindService(logger:ILogger<NorthwindService>, repository:NorthwindRepository)
    + <<async>> FindEmployees(ct:CancellationToken) : Task<employee[]>
    + <<async>> FindCustomers(ct:CancellationToken) : Task<customer[]>
    + <<async>> FindEmployeeById(id:short, ct:CancellationToken) : Task<employee?>
    + <<async>> FindCustomerById(id:string, ct:CancellationToken) : Task<customer?>
}
@enduml
