@startuml NorthwindRepository
class NorthwindRepository {
    - <<readonly>> _logger : ILogger<NorthwindRepository>
    - <<readonly>> _factory : IDbContextFactory<NorthwindContext>
    + NorthwindRepository(logger:ILogger<NorthwindRepository>, factory:IDbContextFactory<NorthwindContext>)
    + <<async>> FetchEmployees(ct:CancellationToken) : Task<employee[]>
    + <<async>> FetchCustomers(ct:CancellationToken) : Task<customer[]>
    + <<async>> FetchEmployeeById(id:short, ct:CancellationToken) : Task<employee?>
    + <<async>> FetchCustomerById(id:string, ct:CancellationToken) : Task<customer?>
    + <<async>> GetById(id:int, ct:CancellationToken) : Task<T?>
    + <<async>> Add(entity:T, ct:CancellationToken) : Task
    + <<async>> Update(entity:T, ct:CancellationToken) : Task
    + <<async>> Delete(entity:T, ct:CancellationToken) : Task
    + <<async>> SaveChangesAsync(ct:CancellationToken) : Task
}
@enduml
