@startuml
class NorthwindController {
    - <<readonly>> _logger : ILogger<NorthwindController>
    - <<readonly>> _service : NorthwindService
    + NorthwindController(logger:ILogger<NorthwindController>, service:NorthwindService)
    + <<async>> GetEmployees(ct:CancellationToken) : Task<IActionResult>
    + <<async>> GetCustomers(ct:CancellationToken) : Task<IActionResult>
    + <<async>> GetEmployee(employeeId:short, ct:CancellationToken) : Task<IActionResult>
    + <<async>> GetCustomer(customerId:string, ct:CancellationToken) : Task<IActionResult>
}
ControllerBase <|-- NorthwindController
@enduml
