version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/"               
    schedule:
      interval: "daily"
    target-branch: "main"        
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "FluentAssertions"
        versions:
          - ">7.0.0"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
    assignees:
      - domoar
    labels:
      - dependencies
