@startuml
class EmployeeController {
    - <<readonly>> _logger : ILogger<EmployeeController>
    - <<readonly>> _service : EmployeeService
    + EmployeeController(logger:ILogger<EmployeeController>, service:EmployeeService)
    + <<async>> GetEmployees(ct:CancellationToken) : Task<IActionResult>
    + <<async>> GetEmployee(employeeId:short, ct:CancellationToken) : Task<IActionResult>
}
ControllerBase <|-- EmployeeController
@enduml
