version: "3.9"

services:
  db:
    user: root
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
      - FOWNER
    volumes:
      - type: bind
        source: C:/DockerVolumes/postgres/tls/key.pem
        target: /var/lib/postgresql/key.pem
      - type: bind
        source: C:/DockerVolumes/postgres/tls/certificate.crt
        target: /var/lib/postgresql/certificate.crt
