@startuml
class ProductService {
    - <<readonly>> _logger : ILogger<ProductService>
    - <<readonly>> _repository : NorthwindRepository
    + ProductService(logger:ILogger<ProductService>, repository:NorthwindRepository)
    + <<async>> Create(product:product, ct:CancellationToken) : Task<product>
    + <<async>> Update(id:int, product:product, ct:CancellationToken) : Task<product?>
    + <<async>> DeleteAsync(id:int, ct:CancellationToken) : Task<bool>
}
@enduml
