name: Generate documentation

permissions:
  contents: write

on:
  workflow_run:
    workflows: [ "CI - Build, Format, Test" ]
    types:
      - completed

jobs:
  generate-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet tool restore

      - name: Generate UML for Controllers, Services & Repositories
        shell: bash
        run: |
          SRC_DIR="./src"  # your real source folder
          OUT_DIR="__extras__/docu/plantuml"
          mkdir -p "$OUT_DIR"
          
          echo "Generating full diagram from $SRC_DIR"
          TEMP_FILE="$OUT_DIR/full.puml"
          OUTPUT_FILE="$OUT_DIR/FilteredClasses.puml"
          
          # 1. Generate full class diagram
          echo "@startuml" > "$TEMP_FILE"
          dotnet tool run puml-gen --output-stdout --no-scope "$SRC_DIR" >> "$TEMP_FILE"
          echo "@enduml" >> "$TEMP_FILE"
          
          # 2. Filter classes
          echo "@startuml" > "$OUTPUT_FILE"
          # keep class declarations and relationships involving Controller, Service, Repository
          grep -E 'class .*Controller|class .*Service|class .*Repository|<\|--|--\|' "$TEMP_FILE" >> "$OUTPUT_FILE"
          echo "@enduml" >> "$OUTPUT_FILE"
          
          # 3. Clean up
          rm "$TEMP_FILE"

      - name: Commit generated diagrams
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update PlantUML diagrams"
          file_pattern: '__extras__/docu/plantuml/*.puml'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          skip_dirty_check: true