name: Generate And Publish Documentation

permissions:
  contents: write
  pages: write
  id-token: write

on:
  workflow_run:
    workflows: [ "CI - Build, Format, Test" ]
    types:
      - completed

jobs:
  generate-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet tool restore

      - name: Generate UML for Controllers, Services & Repositories
        shell: bash
        run: |
          SRC_DIR="."
          OUT_DIR="documentation/plantuml"
          mkdir -p "$OUT_DIR"
          find "$SRC_DIR" -type f \( \
            -name '*Controller.cs' -o \
            -name '*Service.cs'    -o \
            -name '*Repository.cs' \
          \) | while read -r csfile; do
            base=$(basename "$csfile" .cs)
            puml_file="$OUT_DIR/${base}.puml"
            echo "Generating diagram for $csfile → $puml_file"
            dotnet tool run puml-gen "$csfile" "$puml_file"
          done

      - name: Add .nojekyll to allow all files
        run: touch documentation/plantuml/.nojekyll

      - name: Upload UML Diagrams to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/plantuml
          destination_dir: docs/uml
          keep_files: true